import nx from '@nx/eslint-plugin';
import rxjs from '@smarttools/eslint-plugin-rxjs';

export default [
  ...nx.configs['flat/base'],
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [],
          depConstraints: [
            {
              sourceTag: '*',
              onlyDependOnLibsWithTags: ['*'],
            },
          ],
        },
      ],
    },
  },
  ...nx.configs['flat/typescript'],
  {
    files: ['**/*.ts'],
    plugins: { rxjs },
    rules: {
      '@typescript-eslint/consistent-type-definitions': 'error',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/explicit-member-accessibility': [
        'off',
        {
          accessibility: 'explicit',
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      'id-blacklist': 'off',
      'id-match': 'off',
      'no-underscore-dangle': 'off',
      'rxjs/no-ignored-replay-buffer': 'error',
      'rxjs/no-index': 'error',
      'rxjs/no-internal': 'error',
      'rxjs/no-nested-subscribe': 'error',
      'rxjs/no-subject-unsubscribe': 'error',
      'rxjs/no-subject-value': 'error',
      'rxjs/no-unbound-methods': 'error',
    },
  },
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/*.prod.ts',
      // Generated by ts-json-schema-generator + ajv; see
      // libs/plopdown-file/src/schema/README.md. Nx 17 dropped lintFilePatterns
      // from the eslint executor, so .js files in a project are now linted by
      // default and this compiled validator is one huge minified line.
      'libs/plopdown-file/src/schema/*.js',
    ],
  },
];
