/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Information card displayed on the top left, usually at the beginning of a video.
 */
export interface PlopdownInfoSchema {
  type: string;
  title: string;
  url?: string;
  authors: string[];
}
