/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Percentage = number;
export type Degree = number;

/**
 * A simple styled annotation with an icon and some text.
 */
export interface PlopdownPlopSchema {
  type: string;
  top: Percentage;
  left: Percentage;
  width: Percentage;
  desc: string;
  icons: Icon[];
}
export interface Icon {
  top: Percentage;
  left: Percentage;
  size: number;
  rotate: Degree;
  emoji: string;
}
