name: Deploy Website
on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: |-
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true' && steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Website
        run: npm run build website -- --prod

      - name: Build Storybook
        run: npm run nx run plopdown-embed:build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
